### ISSUE TITLE
巧了

### ISSUE THREAD

**Issue by Cloud370** [Drincann/qq-doge-info#1]

**Comment by Cloud370** [comment]
我前边也想写一个bot来看狗狗币行情，结果特么和火箭一样 感觉跟不上波动 就放弃了

**Comment by Cloud370** [comment]
前天0.38买的到0.5 做多75x 结果贪了一波给我强平了 直接卸载哈哈哈

**Comment by Drincann** [comment]
> 前天0.38买的到0.5 做多75x 结果贪了一波给我强平了 直接卸载哈哈哈

玩杠杆啊兄弟

**Comment by Drincann** [comment]
> 前天0.38买的到0.5 做多75x 结果贪了一波给我强平了 直接卸载哈哈哈

准备拿到 8 号看看情况
